# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BoundingBox
                                 A QGIS plugin
 This plugin returns the xmin, ymin, xmax, ymax of the current view window, and the GetMap request of the selected WMS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-07-10
        copyright            : (C) 2019 by Maaka2890
        email                : kkj_15@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BoundingBox class from file BoundingBox.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .BoundingBox import BoundingBox
    return BoundingBox(iface)
